// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA42191Dftm8eARJPSIpLzE_WpZMipv9bM',
    appId: '1:1034356664038:web:94179d7a91a758a5217d27',
    messagingSenderId: '1034356664038',
    projectId: 'ai-financial-agent-150f1',
    authDomain: 'ai-financial-agent-150f1.firebaseapp.com',
    storageBucket: 'ai-financial-agent-150f1.firebasestorage.app',
    measurementId: 'G-3V24WD4YH3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7I8HkH4KrDH_8Rf2XuKfFYPqgBj-K6uc',
    appId: '1:1034356664038:android:da7e68c8e869b74e217d27',
    messagingSenderId: '1034356664038',
    projectId: 'ai-financial-agent-150f1',
    storageBucket: 'ai-financial-agent-150f1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1o07PoSvett_FvYwFer41Q_0IrWoHLkA',
    appId: '1:1034356664038:ios:b2d853d170de45f8217d27',
    messagingSenderId: '1034356664038',
    projectId: 'ai-financial-agent-150f1',
    storageBucket: 'ai-financial-agent-150f1.firebasestorage.app',
    iosClientId: '1034356664038-cema4hb0cb9i4914a3m2csmrkji9qg3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiFinansist',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1o07PoSvett_FvYwFer41Q_0IrWoHLkA',
    appId: '1:1034356664038:ios:b2d853d170de45f8217d27',
    messagingSenderId: '1034356664038',
    projectId: 'ai-financial-agent-150f1',
    storageBucket: 'ai-financial-agent-150f1.firebasestorage.app',
    iosClientId: '1034356664038-cema4hb0cb9i4914a3m2csmrkji9qg3g.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiFinansist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA42191Dftm8eARJPSIpLzE_WpZMipv9bM',
    appId: '1:1034356664038:web:be8f6b3bf62f6545217d27',
    messagingSenderId: '1034356664038',
    projectId: 'ai-financial-agent-150f1',
    authDomain: 'ai-financial-agent-150f1.firebaseapp.com',
    storageBucket: 'ai-financial-agent-150f1.firebasestorage.app',
    measurementId: 'G-93JKK9GHCS',
  );
}
